// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: exthttp/ext_http.proto

package exthttp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncodedHTTPCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *EncodedHTTPCode) Reset() {
	*x = EncodedHTTPCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exthttp_ext_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedHTTPCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedHTTPCode) ProtoMessage() {}

func (x *EncodedHTTPCode) ProtoReflect() protoreflect.Message {
	mi := &file_exthttp_ext_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedHTTPCode.ProtoReflect.Descriptor instead.
func (*EncodedHTTPCode) Descriptor() ([]byte, []int) {
	return file_exthttp_ext_http_proto_rawDescGZIP(), []int{0}
}

func (x *EncodedHTTPCode) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_exthttp_ext_http_proto protoreflect.FileDescriptor

var file_exthttp_ext_http_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x78, 0x74, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x74,
	0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x63, 0x6f, 0x63, 0x6b, 0x72, 0x6f,
	0x61, 0x63, 0x68, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x65, 0x78, 0x74, 0x68, 0x74,
	0x74, 0x70, 0x22, 0x25, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x48, 0x54, 0x54,
	0x50, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x64, 0x6d, 0x65, 0x79, 0x65, 0x72, 0x33,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x78, 0x74, 0x68, 0x74, 0x74, 0x70, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exthttp_ext_http_proto_rawDescOnce sync.Once
	file_exthttp_ext_http_proto_rawDescData = file_exthttp_ext_http_proto_rawDesc
)

func file_exthttp_ext_http_proto_rawDescGZIP() []byte {
	file_exthttp_ext_http_proto_rawDescOnce.Do(func() {
		file_exthttp_ext_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_exthttp_ext_http_proto_rawDescData)
	})
	return file_exthttp_ext_http_proto_rawDescData
}

var file_exthttp_ext_http_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_exthttp_ext_http_proto_goTypes = []interface{}{
	(*EncodedHTTPCode)(nil), // 0: cockroach.errors.exthttp.EncodedHTTPCode
}
var file_exthttp_ext_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exthttp_ext_http_proto_init() }
func file_exthttp_ext_http_proto_init() {
	if File_exthttp_ext_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exthttp_ext_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedHTTPCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exthttp_ext_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exthttp_ext_http_proto_goTypes,
		DependencyIndexes: file_exthttp_ext_http_proto_depIdxs,
		MessageInfos:      file_exthttp_ext_http_proto_msgTypes,
	}.Build()
	File_exthttp_ext_http_proto = out.File
	file_exthttp_ext_http_proto_rawDesc = nil
	file_exthttp_ext_http_proto_goTypes = nil
	file_exthttp_ext_http_proto_depIdxs = nil
}
