// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: errorspb/markers.proto

package errorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarkPayload is the error payload for a forced marker.
// See errors/markers/markers.go and the RFC on
// error handling for details.
type MarkPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg   string           `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Types []*ErrorTypeMark `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *MarkPayload) Reset() {
	*x = MarkPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errorspb_markers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPayload) ProtoMessage() {}

func (x *MarkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_errorspb_markers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPayload.ProtoReflect.Descriptor instead.
func (*MarkPayload) Descriptor() ([]byte, []int) {
	return file_errorspb_markers_proto_rawDescGZIP(), []int{0}
}

func (x *MarkPayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MarkPayload) GetTypes() []*ErrorTypeMark {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_errorspb_markers_proto protoreflect.FileDescriptor

var file_errorspb_markers_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x63, 0x6f, 0x63, 0x6b, 0x72, 0x6f,
	0x61, 0x63, 0x68, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x1a, 0x15, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0b, 0x4d, 0x61, 0x72, 0x6b, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x37, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x63, 0x6b, 0x72, 0x6f, 0x61, 0x63, 0x68, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x64, 0x6d, 0x65,
	0x79, 0x65, 0x72, 0x33, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errorspb_markers_proto_rawDescOnce sync.Once
	file_errorspb_markers_proto_rawDescData = file_errorspb_markers_proto_rawDesc
)

func file_errorspb_markers_proto_rawDescGZIP() []byte {
	file_errorspb_markers_proto_rawDescOnce.Do(func() {
		file_errorspb_markers_proto_rawDescData = protoimpl.X.CompressGZIP(file_errorspb_markers_proto_rawDescData)
	})
	return file_errorspb_markers_proto_rawDescData
}

var file_errorspb_markers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errorspb_markers_proto_goTypes = []interface{}{
	(*MarkPayload)(nil),   // 0: cockroach.errorspb.MarkPayload
	(*ErrorTypeMark)(nil), // 1: cockroach.errorspb.ErrorTypeMark
}
var file_errorspb_markers_proto_depIdxs = []int32{
	1, // 0: cockroach.errorspb.MarkPayload.types:type_name -> cockroach.errorspb.ErrorTypeMark
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_errorspb_markers_proto_init() }
func file_errorspb_markers_proto_init() {
	if File_errorspb_markers_proto != nil {
		return
	}
	file_errorspb_errors_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_errorspb_markers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errorspb_markers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorspb_markers_proto_goTypes,
		DependencyIndexes: file_errorspb_markers_proto_depIdxs,
		MessageInfos:      file_errorspb_markers_proto_msgTypes,
	}.Build()
	File_errorspb_markers_proto = out.File
	file_errorspb_markers_proto_rawDesc = nil
	file_errorspb_markers_proto_goTypes = nil
	file_errorspb_markers_proto_depIdxs = nil
}
